//  jacket object

// id
// title
// description
// gender
// sizes
// baseColor
// price
// discountedPrice
// onSale
// images
// tags
// favorites

var jacket = {
    id: "b8b528fc-6c60-41f6-a5a9-9a8b27a9482a",
    title:  "Rainy Days Akra Jacket",
    description:  "The Women's Rainy Days Akra jacket is bound to be your new go-to water-repellent rain jacket.",
    gender:  "Female",
    sizes:  ["XS", "S", "M", "L", "XL", "XXL"],
    baseColor: "Red",
    price:  129.99,
    discountedPrice:   119.99,
    onSale:  true,
    images:  "https://api.noroff.dev/images/rainy-days/0-akra-jacket.jpg",
    tags:  ["jacket", "womens"],
    favourite:  true
}

    // jacket object

    // id 
    // title
    // description
    // gender
    // sizes
    // baseColor
    // price
    // discountedPrice
    // onSale
    // images
    // tags
    // favourite

    var jacket ={
        id: "97e77845-a485-4301-827f-51b673d4230f",
        title: "Rainy Days M83 Jacket",
        description:  "The Women's Rainy Days M83 jacket delivers waterproof, breathable protection from head to waist. Perfect for the adventure seekers.",
        gender: "Female",
        sizes:  ["XS", "S", "M", "L", "XL", "XXL"],
        baseColor:  "Black",
        price:  109.99,
        discountedPrice:  99.99,
        onSale:  true,
        images:  "https://api.noroff.dev/images/rainy-days/1-m83-jacket.jpg",
        tags:  ["jacket", "womens"],
        favourite:  true
    }

